package com.beaver.drools.example.fact

//
rule "RuleAttributeAgendaGroupExample-1"
agenda-group "agenda-group-1"
when
   $p : Person(age > 20)
then
    System.out.println($p);
end

//
rule "RuleAttributeAgendaGroupExample-2"
agenda-group "agenda-group-2"
when
   $p : Person(age > 30)
then
    System.out.println($p);
    kcontext.getKieRuntime().getAgenda().getAgendaGroup("agenda-group-3").setFocus();
end

//
rule "RuleAttributeAgendaGroupExample-3"
agenda-group "agenda-group-3"
when
   $p : Person(age > 50)
then
    System.out.println($p);
end