package com.beaver.drools.example.fact

import java.util.Date

//=======================
rule "RuleAttributeDynamicSettingExample - 1"
no-loop true
salience 1
when
   $p: Person(age > 20)
then
    System.out.println("age > 20 " + $p);
    modify($p){
        setAge(101)
    }

end

//======================
rule "RuleAttributeDynamicSettingExample - 2"
no-loop true
salience ($p.getAge())
when
   $p: Person(age > 30)
then
   System.out.println("age > 30 " + $p);
end

