package com.beaver.drools.example.fact

import java.util.Date

//=======================
rule "RuleAttributeSalienceExample - 1"
salience -1
when
   $p: Person(age > 20)
then
    System.out.println("age > 20 " + $p);
end

//======================
rule "RuleAttributeSalienceExample - 2"
salience 1
when
   $p: Person(age > 30)
then
   System.out.println("age > 30 " + $p);
end

//=======================
rule "RuleAttributeSalienceExample -3"
salience 10
when
    $p: Date()
then
    System.out.println("不要匹配");
end