 package  com.sample
 
import com.sample.DroolsTest.Message;
import java.math.BigDecimal

 
rule "Hello World"
    when
        m : Message( status == Message.HELLO,  map.getOrDefault("a","") == "A")
    then
        System.out.println( m.getMessage() );
        m.setMessage( "Goodbye cruel world" );
        m.setStatus( Message.GOODBYE );
        update( m );
end

rule "GoodBye"
    when
        Message( status == Message.GOODBYE, myMessage : message )
    then
        System.out.println( myMessage );

end

rule "GoodBye111"
    when
       $m: Message(BigDecimal.valueOf(Double.valueOf(map["amount"])) > 300 * Integer.valueOf(map["days"]))
    then
        System.out.println("h      "+ $m );

end